// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvjqGN5rkWxHKhSPw8jDIXaVyaGSvS5oI',
    appId: '1:160009524746:web:d3087d118b61274980b1f3',
    messagingSenderId: '160009524746',
    projectId: 'fir-test-e561a',
    authDomain: 'fir-test-e561a.firebaseapp.com',
    storageBucket: 'fir-test-e561a.appspot.com',
    measurementId: 'G-HH9GD1CMF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-5gkcXt4hiLfvqjPWbA45gieUgctWA0',
    appId: '1:160009524746:android:1518cc1b3a64a4bf80b1f3',
    messagingSenderId: '160009524746',
    projectId: 'fir-test-e561a',
    storageBucket: 'fir-test-e561a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDCPqfrKaZAcGxIH91-jZQlww9wqu_1Ls',
    appId: '1:160009524746:ios:0ace901c9f1d8c5180b1f3',
    messagingSenderId: '160009524746',
    projectId: 'fir-test-e561a',
    storageBucket: 'fir-test-e561a.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDCPqfrKaZAcGxIH91-jZQlww9wqu_1Ls',
    appId: '1:160009524746:ios:c63f09e4c94b309e80b1f3',
    messagingSenderId: '160009524746',
    projectId: 'fir-test-e561a',
    storageBucket: 'fir-test-e561a.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
